In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model, model_selection
import seaborn as sns
from sklearn.metrics import confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from pickle import dump,load
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, classification_report 
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import backend as Kc
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,InputLayer
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import matthews_corrcoef
from tensorflow.keras.utils import to_categorical

In [2]:

#creamos un dataframe a partir de un dataset
data= pd.read_csv("Filtrado_finalNew.csv",sep=",",index_col=False)


In [3]:
data['Anho']=data['Anho'].values-2012

In [4]:
mod1=['Asignatura Codificada','Cod.Car.Sec Codificado','1P','2P','Taller','Aprobado']
mod2=['Asignatura Codificada','Cod.Car.Sec Codificado','Anho','1P','2P','Taller','Aprobado']
mod3=['Asignatura Codificada','Cod.Car.Sec Codificado','Recursante','1P','2P','Taller','Aprobado']
mod4=['Asignatura Codificada','Cod.Car.Sec Codificado','Recursante','Anho','1P','Taller','Aprobado']
mod5=['Asignatura Codificada','Cod.Car.Sec Codificado','Recursante','Anho','1P','Aprobado']
mod6=['Asignatura Codificada','Cod.Car.Sec Codificado','Recursante','Anho','1P','2P','Aprobado']
mod7=['Asignatura Codificada','Cod.Car.Sec Codificado','Recursante','Anho','1P','2P','Taller','Aprobado']


In [5]:
for features in [mod1,mod2,mod3,mod4,mod5,mod6,mod7]:
    df=data[features]
    print('\n\n')
    print(df.columns)
    X=df.drop('Aprobado',axis=1)
    nb_classes=2
    y=df[['Aprobado']]
    Xnp=np.array(X)
    ynp=np.ravel(np.array(y))
    scaler = MinMaxScaler(feature_range=(0, 1))
    Xnorm = scaler.fit_transform(Xnp)
    x_train, x_test, yLR_train, yLR_test = train_test_split(Xnorm,ynp,test_size=0.20, random_state=33)
    y_train = to_categorical(yLR_train, nb_classes)
    y_test  = to_categorical(yLR_test, nb_classes)
    logreg2 = LogisticRegression()
    logreg2.fit(x_train,yLR_train)
    y_pred=logreg2.predict(x_test)
    print("\nclasses_:\nA list of class labels known to the classifier.\n"+str(logreg2.classes_))
    print("\ncoef_:\nCoefficient of the features in the decision function.\n"+str(logreg2.coef_))
    print("\nintercept_:\nIntercept (a.k.a. bias) added to the decision function.\n"+str(logreg2.intercept_))
    print("\nn_features_in_:\nNumber of features seen during fit.\n"+str(logreg2.n_features_in_))
    print("\nn_iter_:\nActual number of iterations for all classes. If binary or multinomial, it \nreturns only 1 element. For liblinear solver, only the maximum number of \niteration across all classes is given.\n"+str(logreg2.n_iter_))

    matriz2=confusion_matrix(yLR_test,y_pred)
    
    display('Matriz de Confusion:')
    print(matriz2)
    exactitudRL=accuracy_score(yLR_test,y_pred)*100
    print('Exactitud del modelo: ',exactitudRL,' %')
    print("Coeficiente de Matthews de la regresion logistica")
    print(matthews_corrcoef(yLR_test,y_pred))
   




Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', '1P', '2P', 'Taller',
       'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.39723401 -0.09719103  6.93430116  5.52739053  2.00036068]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-2.16582219]

n_features_in_:
Number of features seen during fit.
5

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[13]


'Matriz de Confusion:'

[[11767  4685]
 [ 3117 18709]]
Exactitud del modelo:  79.61753487643033  %
Coeficiente de Matthews de la regresion logistica
0.5812993104015846



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Anho', '1P', '2P',
       'Taller', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.35579655 -0.10724928 -2.21064049  7.05634123  5.66699157  3.36517884]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-1.21663502]

n_features_in_:
Number of features seen during fit.
6

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[22]


'Matriz de Confusion:'

[[11827  4625]
 [ 3129 18697]]
Exactitud del modelo:  79.74293327760071  %
Coeficiente de Matthews de la regresion logistica
0.5839353128570032



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Recursante', '1P',
       '2P', 'Taller', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.40221508  0.01202479  6.1427921   3.55100971  2.76083697 -1.8194852 ]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-6.20660685]

n_features_in_:
Number of features seen during fit.
6

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[35]


'Matriz de Confusion:'

[[11106  5346]
 [  267 21559]]
Exactitud del modelo:  85.3362244631381  %
Coeficiente de Matthews de la regresion logistica
0.7180241525165986



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Recursante', 'Anho',
       '1P', 'Taller', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.42362189  0.0351889   6.59077564 -2.45947935  7.461713    2.61188009]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-5.35468308]

n_features_in_:
Number of features seen during fit.
6

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[21]


'Matriz de Confusion:'

[[11462  4990]
 [  446 21380]]
Exactitud del modelo:  85.7986310674539  %
Coeficiente de Matthews de la regresion logistica
0.7231610868803416



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Recursante', 'Anho',
       '1P', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.47279253  0.02704616  6.65695633 -2.44764613  7.95004939]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-5.32161026]

n_features_in_:
Number of features seen during fit.
5

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[23]


'Matriz de Confusion:'

[[11438  5014]
 [  382 21444]]
Exactitud del modelo:  85.90312973509587  %
Coeficiente de Matthews de la regresion logistica
0.7262188750079172



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Recursante', 'Anho',
       '1P', '2P', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.37710862 -0.01633386  6.29423653 -2.55441692  3.76198569  2.95047073]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-5.26868136]

n_features_in_:
Number of features seen during fit.
6

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[26]


'Matriz de Confusion:'

[[11657  4795]
 [  690 21136]]
Exactitud del modelo:  85.67062019959245  %
Coeficiente de Matthews de la regresion logistica
0.7168881001874253



Index(['Asignatura Codificada', 'Cod.Car.Sec Codificado', 'Recursante', 'Anho',
       '1P', '2P', 'Taller', 'Aprobado'],
      dtype='object')

classes_:
A list of class labels known to the classifier.
[0 1]

coef_:
Coefficient of the features in the decision function.
[[ 0.39559967 -0.01539933  6.29034906 -2.55487789  3.88025832  3.02580092
  -0.96516741]]

intercept_:
Intercept (a.k.a. bias) added to the decision function.
[-5.24406363]

n_features_in_:
Number of features seen during fit.
7

n_iter_:
Actual number of iterations for all classes. If binary or multinomial, it 
returns only 1 element. For liblinear solver, only the maximum number of 
iteration across all classes is given.
[31]


'Matriz de Confusion:'

[[11652  4800]
 [  690 21136]]
Exactitud del modelo:  85.6575578661372  %
Coeficiente de Matthews de la regresion logistica
0.7166422926087832
